{{- if .Values.configuration.traefik }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.application.appName }}-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: cert-manager-acme-issuer
spec:
  rules:
  - host: {{ .Values.configuration.host }}.{{ .Values.configuration.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.application.appName }}
            port:
              number: {{ .Values.configuration.portHTTP }}
  tls:
    - secretName: {{ .Values.application.appName }}-tls
      hosts:
        - {{ .Values.configuration.host }}.{{ .Values.configuration.domain }}
{{- end }}
