apiVersion: v2
name: smarter-cloud
description: smarter cloud deployment chart

home: https://gitlab.com/smarter-project/documentation

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.0.0"
kubeVersion: ">=1.18.0-0"

dependencies:
  - name: cert-manager
    version: v1.10.0
    repository: https://charts.jetstack.io
    alias: cert-manager
    condition: cert-manager.enabled
  - name: "influxdb"
    version: v4.12.0
    repository: https://helm.influxdata.com/
    alias: influxdb
  - name: kube-prometheus-stack
    version: 41.7.0
    repository: https://prometheus-community.github.io/helm-charts
    alias: prometheus
  - name: fluent-bit
    version: 0.20.9
    repository: https://fluent.github.io/helm-charts
    alias: fluent-bit

icon: https://gitlab.com/uploads/-/system/group/avatar/59012546/ARM1636_Project_Logo_ST2_RGB_V1.png
sources:
  - https://gitlab.com/smarter-project/documentation

annotations:
  artifacthub.io/changes: |
    - Initial release
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: |
    - name: Eric Van Hensbergen
      email: ericvh@gmail.com
  artifacthub.io/prerelease: "false"
  artifacthub.io/signKey: |
    fingerprint: 71EDA4E3D652DC73EB09E3A5387D298C169CF24E
    url: https://smarter-project.github.io/documentation/pgp_keys.asc